title: Dewald Krynauw # your name (or website title) here
logo: "/images/logo.png?raw=false" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Computer and Electronics Engineer
  <br><br>
  Masters in Solar Flare prediction with Deep Neural Networks 
  <br><br>
  <a href="https://www.linkedin.com/in/dewald-k-6a080298/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-159223655-1 # your Google Analytics tracking ID here
